- name: Deploy to Optimization Chicken
        uses: easingthemes/ssh-deploy@main
        env:  # <--- 这里必须是 env: ！！！
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete --no-perms --no-owner --no-group"
          SOURCE: "public/"
          REMOTE_HOST: "38.165.45.74"
          REMOTE_USER: "root"
          TARGET: "/var/www/quartz"
          PORT: "2222" # 指定你的安全端口
          SCRIPT_AFTER: |
            chown -R www-data:www-data /var/www/quartz
            chmod -R 755 /var/www/quartz